# Model fit
```{r}
# libraries
library(pacman)
pacman::p_load(
    tidyverse,
    patchwork,
    latex2exp
)
```

```{r}
# empirical data
aliendata <- read_csv("data/AlienData.csv") %>%
    mutate(
        subject = ifelse(condition == 2, subject + 100, subject)
    )
```

## GCM
### load data
```{r}
draws_df <- read_csv("data/gcm_samples.csv") %>%
    mutate(
        chain = as.factor(.chain)
    )
```

### chains
```{r}
chains_df <- draws_df %>%
    filter(subject == 1 | subject == 101) %>%
    mutate(
        condition = ifelse(
            condition == 1,
            "dyad", "individual"
        )
    )

for (ses in seq_len(3)) {
    chains_ses_df <- chains_df %>%
        filter(session == ses)

    p1 <- ggplot(chains_ses_df) +
        geom_line(aes(.iteration, c, color = chain)) +
        theme_bw() +
        facet_wrap(. ~ condition, ncol = 1) +
        scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
        labs(y = "c")

    p2 <- ggplot(chains_ses_df) +
        geom_line(aes(.iteration, w_1, color = chain)) +
        theme_bw() +
        facet_wrap(. ~ condition, ncol = 1) +
        scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
        labs(y = latex2exp::TeX("$w_1$"))

    p3 <- ggplot(chains_ses_df) +
        geom_line(aes(.iteration, w_2, color = chain)) +
        theme_bw() +
        facet_wrap(. ~ condition, ncol = 1) +
        scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
        labs(y = latex2exp::TeX("$w_2$"))

    p4 <- ggplot(chains_ses_df) +
        geom_line(aes(.iteration, w_3, color = chain)) +
        theme_bw() +
        facet_wrap(. ~ condition, ncol = 1) +
        scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
        labs(y = latex2exp::TeX("$w_3$"))

    p5 <- ggplot(chains_ses_df) +
        geom_line(aes(.iteration, w_4, color = chain)) +
        theme_bw() +
        facet_wrap(. ~ condition, ncol = 1) +
        scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
        labs(y = latex2exp::TeX("$w_4$"))

    p6 <- ggplot(chains_ses_df) +
        geom_line(aes(.iteration, w_5, color = chain)) +
        theme_bw() +
        facet_wrap(. ~ condition, ncol = 1) +
        scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
        labs(y = latex2exp::TeX("$w_5$"))

    (p1 + p2) / (p3 + p4) / (p5 + p6) +
        plot_layout(guides = "collect")

    ggsave(
        paste("figs/gcm/chains_iteration_ses",
            ses, ".png",
            sep = ""
        ),
        width = 7, height = 7
    )
}
```

### c parameter
```{r}
draws_df %>%
    filter(subject == 1 | subject == 101) %>%
    mutate(
        condition = ifelse(
            condition == 1,
            "dyad", "individual"
        )
    ) %>%
    ggplot() +
    geom_density(aes(x = c_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = c), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(session ~ condition, ncol = 2) +
    xlab("c")

ggsave("figs/gcm/prior-pos-update-c.png",
    width = 7, height = 7
)
```

```{r}
draws_df %>%
    group_by(
        condition, session, .iteration
    ) %>%
    mutate(
        condition = ifelse(
            condition == 1,
            "dyad", "individual"
        )
    ) %>%
    summarize(
        mean = mean(c)
    ) %>%
    pivot_wider(names_from = condition, values_from = mean) %>%
    mutate(diff = dyad - individual) %>%
    group_by(session) %>%
    summarize(
        mean_ind = mean(individual),
        sd_ind = sd(individual),
        mean_dyad = mean(dyad),
        sd_dyad = sd(dyad),
        mean_diff = mean(diff),
        sd_diff = sd(diff),
        ER = sum(diff > 0) / sum(diff <= 0),
    )
```

```{r}
c_median <- draws_df %>%
    group_by(condition, session, subject) %>%
    summarize(
        mean = mean(c),
        median = median(c),
        sd = sd(c)
    ) %>%
    mutate(
        session = as.factor(session),
        condition = ifelse(
            condition == 1,
            "dyad", "individual"
        )
    )
```

```{r}
ggplot(c_median, aes(
    x = session, y = median,
    color = condition, fill = condition
)) +
    ggdist::stat_halfeye(
        # move to the right
        justification = -0.2,
        # remove the slub interval
        .width = 0,
        point_colour = NA,
        # alpha
        alpha = .5
    ) +
    geom_point(alpha = .5) +
    theme_bw() +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    scale_fill_manual(values = c("darkorange", "slateblue")) +
    labs(y = "c") +
    coord_flip() +
    theme(legend.position = "bottom")

ggsave("figs/gcm/result_c.png",
    width = 7, height = 5
)
```

### w parameters
```{r}
rm(weights_draws_df) # rm in case it is already defined

for (con in unique(draws_df$condition)) {
    for (ses in unique(draws_df$session)) {
        for (sub in unique(draws_df$subject)) {
            weights <- draws_df %>%
                filter(
                    condition == con &
                        session == ses &
                        subject == sub
                ) %>%
                pivot_longer(
                    c("w_1", "w_2", "w_3", "w_4", "w_5"),
                    names_to = "features", values_to = "weights"
                ) %>%
                mutate(feature_number = str_extract(features, "\\d+")) %>%
                select(c(feature_number, weights)) %>%
                mutate(
                    condition = con,
                    session = ses,
                    subject = sub
                )

            weights_prior <- draws_df %>%
                filter(
                    condition == con &
                        session == ses &
                        subject == sub
                ) %>%
                pivot_longer(
                    c("w_prior_1", "w_prior_2", "w_prior_3", "w_prior_4", "w_prior_5"),
                    names_to = "features", values_to = "weights_prior"
                ) %>%
                select(c(weights_prior))

            tmp <- cbind(weights, weights_prior)

            if (exists("weights_draws_df")) {
                weights_draws_df <- rbind(weights_draws_df, tmp)
            } else {
                weights_draws_df <- tmp
            }
        }
    }
}

rm(weights, weights_prior, tmp)
```

```{r}
# add optimal weights

optimal_weights <- list(
    "1" = c(0, 1 / 3, 1 / 4),
    "2" = c(0, 1 / 3, 1 / 4),
    "3" = c(0, 1 / 3, 1 / 4),
    "4" = c(1, 0, 0),
    "5" = c(0, 0, 1 / 4)
)

weights_draws_df <- weights_draws_df %>%
    group_by(session, feature_number) %>%
    mutate(
        s = as.numeric(session),
        optimal_weight = as.numeric(
            optimal_weights[feature_number][[1]][session]
        ),
        weight_diff = weights - optimal_weight
    )
```

```{r}
round_3 <- function(x) {
    return(round(x, 3))
}
for (f in seq_len(5)) {
    col <- paste("w_", f, sep = "")
    results_w <- draws_df %>%
        select(c("condition", "session", ".iteration", col)) %>%
        rename(w = col) %>%
        group_by(
            condition, session, .iteration
        ) %>%
        mutate(
            condition = ifelse(
                condition == 1,
                "dyad", "individual"
            ),
            optimal_weight = as.numeric(
                optimal_weights[f][[1]][session]
            ),
            w_delta = abs(w - optimal_weight)
        ) %>%
        summarize_all(mean) %>%
        select(!w) %>%
        pivot_wider(names_from = condition, values_from = w_delta) %>%
        mutate(diff = individual - dyad) %>%
        group_by(session) %>%
        summarize(
            mean_ind = mean(individual),
            sd_ind = sd(individual),
            mean_dyad = mean(dyad),
            sd_dyad = sd(dyad),
            mean_diff = mean(diff),
            sd_diff = sd(diff),
            ER = sum(diff > 0) / sum(diff <= 0),
            optimal_weight = unique(optimal_weight)
        ) %>%
        mutate_all(round_3)
    print(f)
    print(results_w)
}
```

```{r}
prior_pos_df <- weights_draws_df %>%
    filter(subject == 1 | subject == 101) %>%
    mutate(
        condition = ifelse(
            condition == 1,
            "dyad", "individual"
        )
    )

for (ses in seq_len(3)) {
    prior_pos_df %>%
        filter(session == ses) %>%
        ggplot() +
        geom_density(aes(x = weights_prior), fill = "blue", alpha = .5) +
        geom_density(aes(x = weights), fill = "red", alpha = .5) +
        theme_bw() +
        facet_wrap(feature_number ~ condition, ncol = 2) +
        xlab("weights")

    ggsave(
        paste("figs/gcm/prior-pos-update-w_ses",
            ses, ".png",
            sep = ""
        ),
        width = 7, height = 10
    )
}
```

```{r}
w_median <- weights_draws_df %>%
    group_by(condition, session, subject, feature_number) %>%
    summarize(
        mean = mean(weights),
        median = median(weights),
        sd = sd(weights),
        mean_diff = mean(weight_diff),
        median_diff = median(weight_diff),
        sd_diff = sd(weight_diff),
        optimal = unique(optimal_weight)
    ) %>%
    mutate(
        feature_number = as.factor(feature_number),
        condition = as.factor(condition),
        session = as.factor(session),
        condition = ifelse(
            condition == 1,
            "dyad", "individual"
        )
    )
```

```{r}
ggplot(w_median) +
    ggdist::stat_halfeye(
        aes(
            x = feature_number, y = median,
            fill = condition
        ),
        # move to the right
        justification = -0.2,
        # remove the slub interval
        .width = 0,
        point_colour = NA,
        # alpha
        alpha = .5
    ) +
    geom_point(
        aes(
            x = feature_number, y = median,
            color = condition
        ),
        alpha = .2
    ) +
    geom_point(
        aes(
            x = feature_number, y = optimal
        ),
        shape = 4, size = 3
    ) +
    theme_bw() +
    facet_wrap(. ~ session, ncol = 1) +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    scale_fill_manual(values = c("darkorange", "slateblue")) +
    labs(y = "w", x = "feature dimension") +
    coord_flip() +
    scale_x_discrete(limits = rev) +
    theme(legend.position = "bottom")

ggsave("figs/gcm/result_w.png",
    width = 7, height = 10
)
```

```{r}
ggplot(w_median, aes(
    x = feature_number, y = median_diff,
    color = condition, fill = condition
)) +
    ggdist::stat_halfeye(
        # move to the right
        justification = -0.2,
        # remove the slub interval
        .width = 0,
        point_colour = NA,
        # alpha
        alpha = .5
    ) +
    geom_point(alpha = .5) +
    geom_hline(aes(yintercept = 0),
        linetype = "dashed"
    ) +
    theme_bw() +
    facet_wrap(. ~ session, ncol = 1) +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    scale_fill_manual(values = c("darkorange", "slateblue")) +
    labs(y = "difference", x = "feature dimension") +
    coord_flip()

ggsave("figs/gcm/result_w_diff.png",
    width = 7, height = 10
)
```

### posterior predictions
```{r}
rm(posteriorcorrect)

for (t in seq_len(104)) {
    col <- paste("posteriorcorrect_", t, sep = "")
    tmp <- draws_df %>%
        select(
            "subject", "session",
            "condition", col
        ) %>%
        group_by(subject, condition, session) %>%
        summarize_all(c(mean, sd)) %>%
        mutate(
            correct = fn1,
            sd_correct = fn2,
            trial = t
        ) %>%
        select(!c(fn1, fn2))

    if (exists("posteriorcorrect")) {
        posteriorcorrect <- rbind(
            posteriorcorrect, tmp
        )
    } else {
        posteriorcorrect <- tmp
    }
}
```

```{r}
posteriorcorrect <- posteriorcorrect %>%
    mutate(
        condition = as.factor(condition),
        session = as.factor(session),
        subject = as.factor(subject),
        type = "estimated"
    ) %>%
    group_by(subject, session) %>%
    mutate(
        cumulative = cumsum(correct) / trial
    )

real_correct <- aliendata %>%
    select(c(condition, subject, session, correct, trial)) %>%
    mutate(
        condition = as.factor(condition),
        subject = as.factor(subject),
        session = as.factor(session),
        sd = 0,
        type = "real",
        cumulative = cumsum(correct) / trial
    ) %>%
    group_by(subject, session) %>%
    mutate(
        cumulative = cumsum(correct) / trial
    )

posteriorcorrect <- rbind(posteriorcorrect, real_correct)
```

```{r}
posteriorcorrect %>%
    filter(subject == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    labs(color = "") +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    theme(legend.position = "bottom")

ggsave("figs/gcm/pos_preds_correct_subject_1.png",
    width = 7, height = 5
)
```

```{r}
posteriorcorrect %>%
    filter(subject == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .1
    ) +
    geom_line(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    labs(color = "") +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    theme(legend.position = "bottom")

ggsave("figs/gcm/pos_preds_cumulative_subject_1.png",
    width = 7, height = 5
)
```

```{r}
p1 <- posteriorcorrect %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    labs(color = "") +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    theme(legend.position = "bottom")

ggsave("figs/gcm/pos_preds_correct_condition1.png", p1,
    width = 7, height = 5
)

p2 <- posteriorcorrect %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    labs(color = "") +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    theme(legend.position = "bottom")


ggsave("figs/gcm/pos_preds_correct_condition2.png", p2,
    width = 7, height = 5
)

p1 / p2 +
    plot_layout(guides = "collect")
```

```{r}
p1 <- posteriorcorrect %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .05
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    labs(color = "") +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    theme(legend.position = "bottom")

ggsave("figs/gcm/pos_preds_cumulative_condition1.png", p1,
    width = 7, height = 5
)

p2 <- posteriorcorrect %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .05
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    labs(color = "") +
    scale_color_manual(values = c("darkorange", "slateblue")) +
    theme(legend.position = "bottom")

ggsave("figs/gcm/pos_preds_cumulative_condition2.png", p2,
    width = 7, height = 5
)

p1 / p2 +
    plot_layout(guides = "collect")
```

```{r}
posteriorcorrect %>%
    mutate(
        type = as.factor(type),
        condition = as.factor(ifelse(
            condition == 1,
            "dyad", "individual"
        ))
    ) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type:condition),
        alpha = .03
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type:condition)) +
    theme_bw() +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c(
        "darkorange1", "darkorange4",
        "slateblue1", "slateblue4"
    )) +
    labs(
        y = "cumulative performance",
        color = "") +
    theme(legend.position = "bottom")

ggsave("figs/gcm/pos_preds_cumulative.png",
    width = 7, height = 7
)
```

## Reinforcement Learning (assymetrical)
### load data
```{r}
draws_df <- read_csv("data/rl_samples.csv") %>%
    mutate(
        chain = as.factor(.chain)
    )
```

### Chains
```{r}
p1 <- ggplot(draws_df) +
    geom_line(aes(.iteration, temp, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Temperature")

p2 <- ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_neg, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Alpha Negative")

p3 <- ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_pos, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Alpha Positive")

p <- p1 / p2 / p3
p + plot_annotation(title = "Chain iterations")

ggsave("figs/rl/chain_iterations.png", p, width = 7)
```

```{r}
ggplot(draws_df) +
    geom_line(aes(.iteration, temp, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    facet_wrap(. ~ subject) +
    labs(y = "Temperature") +
    theme(axis.ticks.x = element_blank())

ggsave("figs/rl/chain_iterations_temp.png", width = 7)

ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_neg, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    facet_wrap(. ~ subject) +
    labs(y = "Alpha Negative") +
    theme(axis.ticks.x = element_blank())

ggsave("figs/rl/chain_iterations_alphaneg.png", width = 7)

ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_pos, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    facet_wrap(. ~ subject) +
    labs(y = "Alpha Positive") +
    theme(axis.ticks.x = element_blank())

ggsave("figs/rl/chain_iterations_alphapos.png", width = 7)
```

```{r}
p1 <- ggplot(draws_df) +
    geom_point(
        aes(alpha_neg, alpha_pos, color = chain),
        alpha = 0.1
    ) +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    theme_bw() +
    labs(x = "alpha negative", y = "alpha positive")

p2 <- ggplot(draws_df) +
    geom_point(
        aes(alpha_neg, temp, color = chain),
        alpha = 0.1
    ) +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    theme_bw() +
    labs(x = "alpha negative", y = "temperature")

p3 <- ggplot(draws_df) +
    geom_point(
        aes(alpha_pos, temp, color = chain),
        alpha = 0.1
    ) +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    theme_bw() +
    labs(x = "alpha positive", y = "temperature")

p1 / (p2 + p3)

ggsave("figs/rl/chains_correlation.png", width = 7, height = 7)
```

### Alpha parameters
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_alpha_neg = mean(alpha_neg),
        sd_alpha_neg = sd(alpha_neg),
        mean_alpha_neg_prior = mean(alpha_neg_prior),
        sd_alpha_neg_prior = sd(alpha_neg_prior)
    )
```

```{r}
p <- ggplot(data = draws_df) +
    geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    xlab("Alpha_negative")

p + labs(
    title = "Prior Posterior update: Alpha_negative",
    caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl/prior-pos-update-alphaneg.png", p,
    width = 7, height = 10
)
```

```{r}
p1 <- draws_df %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ session) +
    xlab("Alpha_negative") +
    labs(title = "A) Condition 1")

p2 <- draws_df %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ session) +
    xlab("Alpha_negative") +
    labs(title = "B) Condition 2")

p1 / p2

ggsave("figs/rl/prior-pos-update-alphaneg-condition.png",
    width = 7, height = 5
)
```

```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_alpha_pos = mean(alpha_pos),
        sd_alpha_pos = sd(alpha_pos),
        mean_alpha_pos_prior = mean(alpha_pos_prior),
        sd_alpha_pos_prior = sd(alpha_pos_prior)
    )
```

```{r}
p <- ggplot(data = draws_df) +
    geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    xlab("Alpha_positive")

p + labs(
    title = "Prior Posterior update: Alpha_positive",
    caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl/prior-pos-update-alphapos.png", p,
    width = 7, height = 10
)
```

```{r}
p1 <- draws_df %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ session) +
    xlab("Alpha_negative") +
    labs(title = "A) Condition 1")

p2 <- draws_df %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ session) +
    xlab("Alpha_negative") +
    labs(title = "B) Condition 2")

p1 / p2

ggsave("figs/rl/prior-pos-update-alphapos-condition.png",
    width = 7, height = 5
)
```

### Temperature
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_temp = mean(temp),
        sd_temp = sd(temp),
        mean_temp_prior = mean(temp_prior),
        sd_temp_prior = sd(temp_prior)
    )
```

```{r}
p <- ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    xlab("Temperature")

p + labs(
    title = "Prior Posterior update: Temperature",
    caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl/prior-pos-update-temp.png", p,
    width = 7, height = 10
)
```

```{r}
p1 <- draws_df %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ session) +
    xlab("Temperature") +
    labs(title = "A) Condition 1")

p2 <- draws_df %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ session) +
    xlab("Temperature") +
    labs(title = "B) Condition 2")

p1 / p2

ggsave("figs/rl/prior-pos-update-temp-condition.png", p,
    width = 7, height = 5
)
```

### Posterior prediction
```{r}
rm(posteriorcorrect)

for (t in seq_len(104)) {
    col <- paste("posteriorcorrect_", t, sep = "")
    tmp <- draws_df %>%
        select(
            "subject", "session",
            "condition", col
        ) %>%
        group_by(subject, condition, session) %>%
        summarize_all(c(mean, sd)) %>%
        mutate(
            correct = fn1,
            sd_correct = fn2,
            trial = t
        ) %>%
        select(!c(fn1, fn2))

    if (exists("posteriorcorrect")) {
        posteriorcorrect <- rbind(
            posteriorcorrect, tmp
        )
    } else {
        posteriorcorrect <- tmp
    }
}
```

```{r}
posteriorcorrect <- posteriorcorrect %>%
    mutate(
        condition = as.factor(condition),
        session = as.factor(session),
        subject = as.factor(subject),
        type = "estimated"
    ) %>%
    group_by(subject, session) %>%
    mutate(
        cumulative = cumsum(correct) / trial
    )

real_correct <- aliendata %>%
    select(c(condition, subject, session, correct, trial)) %>%
    mutate(
        condition = as.factor(condition),
        subject = as.factor(subject),
        session = as.factor(session),
        sd = 0,
        type = "real",
        cumulative = cumsum(correct) / trial
    ) %>%
    group_by(subject, session) %>%
    mutate(
        cumulative = cumsum(correct) / trial
    )

posteriorcorrect <- rbind(posteriorcorrect, real_correct)
```

```{r}
ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    scale_color_manual(values = c("darkorange", "slateblue"))

ggsave("figs/rl/pos_preds_correct_subject.png",
    width = 7
)
```

```{r}
p1 <- posteriorcorrect %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    labs(title = "A) Condition 1") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p2 <- posteriorcorrect %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    labs(title = "B) Condition 2") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p1 / p2 +
    plot_layout(guides = "collect")

ggsave("figs/rl/pos_preds_correct_condition.png",
    width = 7, height = 5
)
```

```{r}
ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .1
    ) +
    geom_line(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    scale_color_manual(values = c("darkorange", "slateblue"))

ggsave("figs/rl/pos_preds_cumulative_subject.png",
    width = 7
)
```

```{r}
p1 <- posteriorcorrect %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .05
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    labs(title = "A) Condition 1") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p2 <- posteriorcorrect %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .05
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    labs(title = "B) Condition 2") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p1 / p2 +
    plot_layout(guides = "collect")

ggsave("figs/rl/pos_preds_cumulative_condition.png",
    width = 7, height = 5
)
```

## Reinforcement Learning (simple)
### load data
```{r}
draws_df <- read_csv("data/rl_simple_samples.csv") %>%
    mutate(
        chain = as.factor(.chain)
    )
```

### Chains
```{r}
p1 <- ggplot(draws_df) +
    geom_line(aes(.iteration, temp, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Temperature")

p2 <- ggplot(draws_df) +
    geom_line(aes(.iteration, alpha, color = chain)) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Alpha")

p1 / p2 +
    plot_annotation(title = "Chain iterations")

ggsave("figs/rl_simple/chain_iterations.png",
    width = 7
)
```

```{r}
ggplot(draws_df) +
    geom_line(aes(.iteration, temp, color = chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Temperature")

ggsave("figs/rl_simple/chain_iterations_temp.png",
    width = 7
)

ggplot(draws_df) +
    geom_line(aes(.iteration, alpha, color = chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(y = "Alpha")

ggsave("figs/rl_simple/chain_iterations_alpha.png",
    width = 7
)
```

```{r}
ggplot(draws_df) +
    geom_point(
        aes(alpha, temp, color = chain),
        alpha = 0.1
    ) +
    theme_bw() +
    scale_color_manual(values = c("dodgerblue4", "deepskyblue")) +
    labs(x = "alpha", y = "temperature")

ggsave("figs/rl_simple/chains_correlation.png", width = 7, height = 7)
```

### Alpha parameter
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_alpha = mean(alpha),
        sd_alpha = sd(alpha),
        mean_alpha_prior = mean(alpha_prior),
        sd_alpha_prior = sd(alpha_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    xlab("Alpha")

ggsave("figs/rl_simple/prior-pos-update-alpha.png", width = 7)
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    xlab("Alpha")

ggsave("figs/rl_simple/prior-pos-update-alpha-condtion.png", width = 7)
```

Temperature
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_temp = mean(temp),
        sd_temp = sd(temp),
        mean_temp_prior = mean(temp_prior),
        sd_temp_prior = sd(temp_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    xlab("Temperature")

ggsave("figs/rl_simple/prior-pos-update-temp.png", width = 7)
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    xlab("Temperature")

ggsave("figs/rl_simple/prior-pos-update-temp-condition.png", width = 7)
```

### Posterior predictions
```{r}
rm(posteriorcorrect)

for (t in 1:104) {
    for (ses in unique(draws_df$session)) {
        for (sub in unique(draws_df$subject)) {
            tmp_draws <- draws_df %>%
                filter(
                    subject == sub &
                        session == ses
                )
            col <- paste("tmp_draws$posteriorcorrect_", t, sep = "")
            colvalues <- eval(parse(text = col))
            mean_correct <- mean(colvalues)
            sd_correct <- sd(colvalues)
            tmp <- tibble(
                correct = mean_correct,
                sd = sd_correct,
                trial = t,
                condition = unique(tmp_draws$condition),
                subject = sub,
                session = ses
            )

            if (exists("posteriorcorrect")) {
                posteriorcorrect <- rbind(
                    posteriorcorrect, tmp
                )
            } else {
                posteriorcorrect <- tmp
            }
        }
    }
}
```

```{r}
rm(posteriorcorrect)

for (t in seq_len(104)) {
    col <- paste("posteriorcorrect_", t, sep = "")
    tmp <- draws_df %>%
        select(
            "subject", "session",
            "condition", col
        ) %>%
        group_by(subject, condition, session) %>%
        summarize_all(c(mean, sd)) %>%
        mutate(
            correct = fn1,
            sd_correct = fn2,
            trial = t
        ) %>%
        select(!c(fn1, fn2))

    if (exists("posteriorcorrect")) {
        posteriorcorrect <- rbind(
            posteriorcorrect, tmp
        )
    } else {
        posteriorcorrect <- tmp
    }
}
```

```{r}
posteriorcorrect <- posteriorcorrect %>%
    mutate(
        condition = as.factor(condition),
        session = as.factor(session),
        subject = as.factor(subject),
        type = "estimated"
    ) %>%
    group_by(subject, session) %>%
    mutate(
        cumulative = cumsum(correct) / trial
    )

real_correct <- aliendata %>%
    select(c(condition, subject, session, correct, trial)) %>%
    mutate(
        condition = as.factor(condition),
        subject = as.factor(subject),
        session = as.factor(session),
        sd = 0,
        type = "real",
        cumulative = cumsum(correct) / trial
    ) %>%
    group_by(subject, session) %>%
    mutate(
        cumulative = cumsum(correct) / trial
    )

posteriorcorrect <- rbind(posteriorcorrect, real_correct)
```

```{r}
ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    scale_color_manual(values = c("darkorange", "slateblue"))

ggsave("figs/rl_simple/pos_preds_correct_subject.png",
    width = 7
)
```

```{r}
p1 <- posteriorcorrect %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    labs(title = "A) Condition 1") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p2 <- posteriorcorrect %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_point(aes(x = trial, y = correct, color = type),
        alpha = .1
    ) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() +
    labs(title = "B) Condition 2") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p1 / p2 +
    plot_layout(guides = "collect")

ggsave("figs/rl_simple/pos_preds_correct_condition.png",
    width = 7
)
```

```{r}
ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .1
    ) +
    geom_line(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    scale_color_manual(values = c("darkorange", "slateblue"))

ggsave("figs/rl_simple/pos_preds_cumulative_subject.png",
    width = 7
)
```

```{r}
p1 <- posteriorcorrect %>%
    filter(condition == 1) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .05
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    labs(title = "A) Condition 1") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p2 <- posteriorcorrect %>%
    filter(condition == 2) %>%
    ggplot() +
    geom_point(aes(x = trial, y = cumulative, color = type),
        alpha = .05
    ) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() +
    labs(title = "B) Condition 2") +
    facet_wrap(. ~ session) +
    scale_color_manual(values = c("darkorange", "slateblue"))

p1 / p2 +
    plot_layout(guides = "collect")

ggsave("figs/rl_simple/pos_preds_cumulative_condition.png",
    width = 7
)
```
