# Model recovery

```{r}
# libraries
library(pacman)
pacman::p_load(
    tidyverse
)
```

```{r}
# load data
compare_df <- read_csv("data/recovery/model_recovery_compare.csv")
pointwise_df <- read_csv("data/recovery/model_recovery_pointwise.csv")

# add model names for plotting and NA for inf pareto k values
model_names <- list(
    "gcm" = "GCM",
    "rl" = "RL Asymmetrical",
    "rl_simple" = "RL Simple"
)

pointwise_df <- pointwise_df %>%
    mutate(
        true_model_names = as.character(model_names[true_model]),
        model_name = as.character(model_names[model]),
        influence_pareto_k = ifelse(
            is.infinite(influence_pareto_k), NA, influence_pareto_k
        )
    )

compare_df <- compare_df %>%
    mutate(
        model_name = as.character(model_names[model])
    )
```

## PSIS diagnostic
```{r}
ggplot(data = pointwise_df) +
    geom_point(aes(x = trial, y = influence_pareto_k, color = model_name),
        alpha = .2
    ) +
    facet_wrap(. ~ true_model_names) +
    geom_hline(
        yintercept = 0,
        linetype = "dashed", linewidth = 1
    ) +
    geom_hline(
        yintercept = 0.5,
        linetype = "dashed", linewidth = 1
    ) +
    geom_hline(
        yintercept = 0.7,
        linetype = "dashed", linewidth = 1
    ) +
    theme_bw() +
    labs(
        x = "",
        y = "Pareto k",
        color = "Model"
    ) +
    scale_color_brewer(palette = "Dark2")

ggsave("figs/model_recovery/psis_diagnostics.png",
    width = 7, height = 5
)
```

## compare
```{r}
compare_df %>%
    filter(true_model == "gcm") %>%
    select(model, looic, index)

compare_df %>%
    filter(true_model == "rl") %>%
    select(model, looic, index)

compare_df %>%
    filter(true_model == "rl_simple") %>%
    select(model, looic, index)
```

```{r}
compare_df <- compare_df %>%
    group_by(index, true_model) %>%
    mutate(
        model_rank = ifelse(
            looic == min(looic), 1,
            ifelse(looic == max(looic), 3, 2)
        ),
        true_model_rank = ifelse(
            model == true_model,
            1, 0
        )
    )

compare_df %>%
    group_by(true_model, model) %>%
    summarize(
        mean(model_rank == 1),
        sum(model_rank == 1),
        mean(model_weights),
        sd(model_weights)
    )
```

```{r}
cm <- compare_df %>%
    group_by(true_model, model) %>%
    summarize(
        freq = sum(model_rank == 1)
    ) %>%
    mutate(
        model = factor(model_names[model],
            level = c(
                "RL Simple", "RL Asymmetrical", "GCM"
            )
        ),
        true_model = factor(model_names[true_model],
            level = c(
                "GCM", "RL Asymmetrical", "RL Simple"
            )
        )
    )

ggplot(cm, aes(true_model, model, fill = freq)) +
    geom_tile() +
    geom_text(aes(label = freq)) +
    theme_bw() +
    scale_fill_gradient(low = "white", high = "steelblue") +
    labs(
        x = "True Model",
        y = "Best Model Fit"
    ) +
    theme(legend.position = "none")

ggsave("figs/model_recovery/model_rank_confusion_matrix.png",
    width = 7, height = 7
)
```

## elpd diff
```{r}
elpd_diff <- pointwise_df %>%
    select(c(elpd_loo, model, trial, true_model_names, index)) %>%
    pivot_wider(names_from = model, values_from = elpd_loo) %>%
    mutate(
        rl_asym_rl_simple_diff = rl - rl_simple,
        rl_asym_gcm_diff = rl - gcm,
        rl_simple_gcm_diff = rl_simple - gcm
    )
```

```{r}
ggplot(data = elpd_diff) +
    geom_point(aes(x = trial, y = rl_asym_rl_simple_diff),
        alpha = .2
    ) +
    geom_hline(
        yintercept = 0, color = "orange",
        linetype = "dashed", linewidth = 1
    ) +
    facet_wrap(. ~ true_model_names) +
    theme_bw() +
    labs(
        x = "",
        y = "elpd difference"
    )

ggsave("figs/model_recovery/elpd_diff_rl_asym_rl_simple.png",
    width = 7, height = 5
)
```

```{r}
ggplot(data = elpd_diff) +
    geom_point(aes(x = trial, y = rl_asym_gcm_diff),
        alpha = .2
    ) +
    geom_hline(
        yintercept = 0, color = "orange",
        linetype = "dashed", linewidth = 1
    ) +
    facet_wrap(. ~ true_model_names) +
    theme_bw() +
    labs(
        x = "",
        y = "elpd difference"
    )

ggsave("figs/model_recovery/elpd_diff_rl_asym_gcm.png",
    width = 7, height = 5
)
```

```{r}
ggplot(data = elpd_diff) +
    geom_point(aes(x = trial, y = rl_simple_gcm_diff),
        alpha = .2
    ) +
    geom_hline(
        yintercept = 0, color = "orange",
        linetype = "dashed", linewidth = 1
    ) +
    facet_wrap(. ~ true_model_names) +
    theme_bw() +
    labs(
        x = "",
        y = "elpd difference"
    )

ggsave("figs/model_recovery/elpd_diff_rl_simple_gcm.png",
    width = 7, height = 5
)
```