# Model comparison
```{r}
# libraries
library(pacman)
pacman::p_load(
    tidyverse,
    patchwork
)
```

```{r}
# load data
sessions <- c(1, 2, 3)

for (ses in sessions) {
    pointwise_tmp <- read_csv(
        paste("data/model_comparison_pointwise_", ses, ".csv", sep = "")
    ) %>%
        mutate(
            trial = rep(
                seq_len(104),
                length(unique(subject)) * length(unique(model))
            ),
            condition = ifelse(subject > 100, 2, 1)
        )
    pointwise_tmp$session <- ses

    if (exists("pointwise_df")) {
        pointwise_df <- rbind(pointwise_df, pointwise_tmp)
    } else {
        pointwise_df <- pointwise_tmp
    }

    compare_tmp <- read_csv(
        paste("data/model_comparison_compare_", ses, ".csv", sep = "")
    ) %>%
        mutate(
            condition = ifelse(subject > 100, 2, 1)
        )
    compare_tmp$session <- ses

    if (exists("compare_df")) {
        compare_df <- rbind(compare_df, compare_tmp)
    } else {
        compare_df <- compare_tmp
    }
}

# add model names for plotting and NA for inf pareto k values
model_names <- list(
    "gcm" = "GCM",
    "rl" = "RL Asymmetrical",
    "rl_simple" = "RL Simple"
)

pointwise_df <- pointwise_df %>%
    mutate(
        model_name = as.character(model_names[model]),
        influence_pareto_k = ifelse(
            is.infinite(influence_pareto_k), NA, influence_pareto_k
        )
    )

compare_df <- compare_df %>%
    mutate(
        model_name = as.character(model_names[model])
    )
```

## PSIS diagnostic
```{r}
pointwise_df <- pointwise_df %>%
    mutate(
        critical_psis = ifelse(
            influence_pareto_k > .7 | is.na(influence_pareto_k),
            1, 0
        )
    )

pointwise_df %>%
    group_by(model) %>%
    summarize(
        mean(critical_psis)
    )
```

```{r}
ggplot(data = pointwise_df) +
    geom_point(aes(x = trial, y = influence_pareto_k, color = model_name),
        alpha = .2
    ) +
    geom_hline(
        yintercept = 0,
        linetype = "dashed", linewidth = 1
    ) +
    geom_hline(
        yintercept = 0.5,
        linetype = "dashed", linewidth = 1
    ) +
    geom_hline(
        yintercept = 0.7,
        linetype = "dashed", linewidth = 1
    ) +
    theme_bw() +
    labs(
        x = "",
        y = "Pareto k",
        color = "Model"
    ) +
    scale_color_brewer(palette = "Dark2") +
    theme(legend.position = "bottom")

ggsave("figs/model_comparison/psis_diagnostics.png",
    width = 7, height = 7
)
```

```{r}
ggplot(data = pointwise_df) +
    geom_point(aes(x = trial, y = influence_pareto_k, color = model_name),
        alpha = .5
    ) +
    facet_wrap(. ~ subject) +
    geom_hline(
        yintercept = 0,
        linetype = "dashed", linewidth = 1
    ) +
    geom_hline(
        yintercept = 0.5,
        linetype = "dashed", linewidth = 1
    ) +
    geom_hline(
        yintercept = 0.7,
        linetype = "dashed", linewidth = 1
    ) +
    theme_bw() +
    labs(
        x = "",
        y = "Pareto k",
        color = "Model"
    ) +
    scale_color_brewer(palette = "Dark2")

ggsave("figs/model_comparison/psis_diagnostics_subject.png",
    width = 7, height = 10
)
```

## compare
```{r}
compare_df <- compare_df %>%
    group_by(condition, session, subject) %>%
    mutate(
        model_rank = ifelse(
            looic == min(looic), 1,
            ifelse(looic == max(looic), 3, 2)
        ),
        condition = ifelse(condition == 1,
            "dyad", "individual"
        )
    )

# best ranking model
compare_df %>%
    group_by(condition, session, model) %>%
    summarize(
        mean = mean(model_rank == 1),
        total = sum(model_rank == 1)
    )

# second and third best ranking model
compare_df %>%
    mutate(
        win_model = compare_df[
            compare_df$session == session &
            compare_df$subject == subject &
            compare_df$model_rank == 1,
        ]$model
    ) %>%
    filter(win_model != "gcm") %>%
    group_by(condition, session, model) %>%
    summarize(
        total2 = sum(model_rank == 2),
        total3 = sum(model_rank == 3)
    )
```

se_diff
```{r}
compare_df %>%
    filter(elpd_diff != 0) %>%
    mutate(
        se_magnitude = abs(elpd_diff) - 2 * se_diff
    ) %>%
    group_by(condition, session, model) %>%
    summarize(
        mean(se_magnitude),
        sd(se_magnitude),
        n()
    )
```

```{r}
gcm_winning <- compare_df %>%
    filter(model == "gcm" & model_rank == 1) %>%
    select(c(subject, session)) %>%
    mutate(
        subject_session = paste(
            subject, "_", session,
            paste = ""
        )
    )

gcm_not_winning <- compare_df %>%
    filter(model == "gcm" & model_rank != 1) %>%
    select(c(subject, session)) %>%
    mutate(
        subject_session = paste(
            subject, "_", session,
            paste = ""
        )
    )

compare_df %>%
    mutate(
        subject_session = paste(
            subject, "_", session,
            paste = ""
        ),
        se_magnitude = abs(elpd_diff) - 2 * se_diff
    ) %>%
    filter(
        subject_session %in% gcm_winning$subject_session
    ) %>%
    group_by(condition, session, model) %>%
    summarize(
        mean(se_magnitude),
        sd(se_magnitude),
        n()
    )

compare_df %>%
    mutate(
        subject_session = paste(
            subject, "_", session,
            paste = ""
        ),
        se_magnitude = abs(elpd_diff) - 2 * se_diff
    ) %>%
    filter(
        subject_session %in% gcm_not_winning$subject_session
    ) %>%
    group_by(condition, session, model) %>%
    summarize(
        mean(se_magnitude),
        n()
    )
```

stacking weights
```{r}
compare_df %>%
    mutate(
        session = as.factor(session)
    ) %>%
    group_by(condition, session, model_name) %>%
    summarize(
        weights = mean(model_weights),
        sd = sd(model_weights)
    ) %>%
    ggplot() +
    geom_point(
        aes(x = session, y = weights, color = model_name),
        size = 3
    ) +
    geom_line(
        aes(x = session, y = weights,
            group = model_name, color = model_name),
        linetype = "dashed"
    ) +
    geom_errorbar(
        aes(
            session,
            ymin = weights - sd,
            ymax = weights + sd,
            color = model_name),
            width = .2, alpha = .7
    ) +
    facet_wrap(. ~ condition) +
    theme_bw() +
    labs(color = "Model") +
    scale_color_brewer(palette = "Dark2") +
    theme(legend.position = "bottom")

ggsave("figs/model_comparison/model_weights.png",
       width = 7, height = 5)
```

Results matrices
```{r}
cm <- compare_df %>%
    group_by(session, model_name, condition) %>%
    summarize(
        freq = sum(model_rank == 1),
        weight = mean(model_weights)
    )

ggplot(cm, aes(model_name, session, fill = freq)) +
    geom_tile() +
    geom_text(aes(label = freq)) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    scale_fill_gradient(low = "white", high = "palegreen4") +
    labs(
        x = "model",
        y = "session"
    ) +
    theme(legend.position = "none")

ggsave("figs/model_comparison/model_rank_matrix.png",
    width = 7, height = 4
)
```

```{r}
ggplot(cm, aes(model_name, session, fill = weight)) +
    geom_tile() +
    geom_text(aes(label = round(weight, 3))) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    scale_fill_gradient(low = "white", high = "palegreen4") +
    labs(
        x = "model",
        y = "session"
    ) +
    theme(legend.position = "none")

ggsave("figs/model_comparison/model_weight_matrix.png",
    width = 7, height = 4
)
```

## elpd diff
```{r}
elpd_diff <- pointwise_df %>%
    select(c(elpd_loo, model, trial, subject, condition, session)) %>%
    pivot_wider(names_from = model, values_from = elpd_loo) %>%
    mutate(
        rl_asym_rl_simple_diff = rl - rl_simple,
        rl_asym_gcm_diff = rl - gcm,
        rl_simple_gcm_diff = rl_simple - gcm,
        session = as.factor(session)
    )
```

```{r}
ggplot(data = elpd_diff) +
    geom_point(aes(x = trial, y = rl_asym_rl_simple_diff, color = session),
        alpha = .5
    ) +
    geom_hline(
        yintercept = 0, color = "black",
        linetype = "dashed", linewidth = 1
    ) +
    facet_wrap(. ~ condition) +
    theme_bw() +
    labs(
        x = "",
        y = "elpd difference"
    ) +
    scale_color_brewer(palette = "Dark2")

ggsave("figs/model_comparison/elpd_diff_rl_asym_rl_simple.png",
    width = 7, height = 5
)
```

```{r}
ggplot(data = elpd_diff) +
    geom_point(aes(x = trial, y = rl_asym_gcm_diff, color = session),
        alpha = .5
    ) +
    geom_hline(
        yintercept = 0, color = "black",
        linetype = "dashed", linewidth = 1
    ) +
    facet_wrap(. ~ condition) +
    theme_bw() +
    labs(
        x = "",
        y = "elpd difference"
    ) +
    scale_color_brewer(palette = "Dark2")

ggsave("figs/model_comparison/elpd_diff_rl_asym_gcm.png",
    width = 7, height = 5
)
```

```{r}
ggplot(data = elpd_diff) +
    geom_point(aes(x = trial, y = rl_simple_gcm_diff, color = session),
        alpha = .5
    ) +
    geom_hline(
        yintercept = 0, color = "black",
        linetype = "dashed", linewidth = 1
    ) +
    facet_wrap(. ~ condition) +
    theme_bw() +
    labs(
        x = "",
        y = "elpd difference"
    ) +
    scale_color_brewer(palette = "Dark2")

ggsave("figs/model_comparison/elpd_diff_rl_simple_gcm.png",
    width = 7, height = 5
)
```