# Parameter recovery 

```{r}
# libraries
library(pacman)
pacman::p_load(
  tidyverse,
  patchwork,
  RColorBrewer,
  latex2exp
)
```

## GCM
### load data
```{r}
nobservations <- c(104, 208, 312)

rm(recovery_df) # remove in case it is already defined
# read df
for (nobs in nobservations) {
  tmp <- read_csv(
    paste("data/recovery/parameter_recovery_gcm_binary",
      nobs, "_1.csv",
      sep = ""
    )
  )

  if (exists("recovery_df")) {
    recovery_df <- rbind(recovery_df, tmp)
  } else {
    recovery_df <- tmp
  }
}

recovery_df <- recovery_df %>% 
    mutate(
      nobservations = as.factor(nobservations)
    )
```

### inspection
```{r}
recovery_df %>%
  group_by(c_parameter) %>%
  summarize(
    mean_c = mean(c),
    sd_c = sd(c),
    mean_c_prior = mean(c_prior),
    sd_c_prior = sd(c_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(aes(x = c_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = c), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = c_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ c_parameter) +
  xlab("C")

p + labs(
    title = "Prior Posterior update: C parameter",
    caption = "Prior (blue) and posterior (red)"
  )

ggsave("figs/gcm/parameter_recovery/pos-prior-update-c.png", p,
  width = 7, height = 5
)
```

```{r}
recovery_df %>%
  group_by(c_parameter, w_parameter) %>%
  summarize(
    mean_c = mean(c),
    sd_c = sd(c),
    mean_c_prior = mean(c_prior),
    sd_c_prior = sd(c_prior)
  )
```

```{r}
ggplot(data = recovery_df) +
  geom_density(aes(x = c, fill = w_parameter), alpha = .5) +
  # geom_vline(aes(xintercept = c_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ c_parameter, scales = "free") +
  scale_fill_manual(values = c("darkorange2", "purple")) +
  labs(
    x = "c",
    fill = "w parameters"
  ) +
  ylim(0, 190) + xlim(0, 0.1) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos-c_by_w.png",
  width = 7, height = 5
)
```

```{r}
ggplot(data = recovery_df) +
  geom_density(aes(x = c, fill = nobservations), alpha = .5) +
  # geom_vline(aes(xintercept = c_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ c_parameter, scales = "free") +
  scale_fill_brewer(palette = "Dark2") +
  labs(
    x = "c",
    fill = "Number of observations"
  ) +
  ylim(0, 500) + xlim(0, 0.1) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos-c_by_nobs.png",
  width = 7, height = 5
)
```

```{r}
rm(weights_draws_df) # rm in case it is already defined

c_parameters <- unique(recovery_df$c_parameter)
w_parameters <- unique(recovery_df$w_parameter)
nobservations <- unique(recovery_df$nobservations)

for (c_param in c_parameters) {
  for (w_params in w_parameters) {
    for (nobs in nobservations) {
      weights <- recovery_df %>%
        filter(
          c_parameter == c_param &
          w_parameter == w_params &
          nobservations == nobs) %>%
        pivot_longer(
          c("w_1", "w_2", "w_3", "w_4", "w_5"),
          names_to = "features", values_to = "weights"
        ) %>%
        mutate(feature_number = str_extract(features, "\\d+")) %>%
        select(c(feature_number, weights)) %>%
        mutate(
          w_parameter = as.numeric(
            str_split(w_params, ",")[[1]]
            )[as.integer(feature_number)],
          w_param_cond = w_params,
          c_parameter = c_param,
          nobservations = nobs
        )
      
      weights_prior <- recovery_df %>%
        filter(
          c_parameter == c_param &
          w_parameter == w_params &
          nobservations == nobs) %>%
        pivot_longer(
          c("w_prior_1", "w_prior_2", "w_prior_3", "w_prior_4", "w_prior_5"),
          names_to = "features", values_to = "weights_prior"
        ) %>%
        select(c(weights_prior))
      
      tmp <- cbind(weights, weights_prior)

      if (exists("weights_draws_df")) {
        weights_draws_df <- rbind(weights_draws_df, tmp)
      } else {
        weights_draws_df <- tmp
      }
    }
  }
}

rm(weights, weights_prior, tmp)
```

```{r}
weights_draws_df %>%
  group_by(w_param_cond, feature_number) %>%
  summarize(
    w_mean = mean(weights),
    sd_w = sd(weights),
    w_prior_mean = mean(weights_prior),
    sd_w_prior = sd(weights_prior),
    true_w = unique(w_parameter)
  )
```

```{r}
weights_draws_df %>%
  filter(w_param_cond == "1,0,0,0,0") %>%
  ggplot() +
  geom_density(
    aes(x = weights_prior),
    alpha = .5, fill = "blue"
  ) +
  geom_density(
    aes(x = weights),
    alpha = .5, fill = "red"
  ) +
  geom_vline(
    aes(xintercept = w_parameter),
    linetype = "dashed"
    ) +
  theme_bw() +
  labs(x = "weight") +
  facet_wrap(. ~ feature_number)

ggsave("figs/gcm/parameter_recovery/pos-prior-update_w_1.png",
       width = 7, height = 5) 
```

```{r}
weights_draws_df %>%
  filter(w_param_cond == "0.2,0.2,0.2,0.2,0.2") %>%
  ggplot() +
  geom_density(
    aes(x = weights_prior),
    alpha = .5, fill = "blue"
  ) +
  geom_density(
    aes(x = weights),
    alpha = .5, fill = "red"
  ) +
  geom_vline(
    aes(xintercept = w_parameter),
    linetype = "dashed"
    ) +
  theme_bw() +
  labs(x = "weight") +
  facet_wrap(. ~ feature_number)

ggsave("figs/gcm/parameter_recovery/pos-prior-update_w_2.png",
       width = 7, height = 5)
```

```{r}
ggplot(data = weights_draws_df) +
  geom_density(
    aes(
      x = weights, fill = w_param_cond
    ),
    alpha = .3
  ) +
  geom_vline(
    aes(xintercept = w_parameter, color = w_param_cond),
    linetype = "dashed"
    ) +
  theme_bw() +
  facet_wrap(. ~ feature_number) +
  scale_fill_manual(values = c("darkorange2", "purple")) +
  scale_color_manual(values = c("darkorange2", "purple")) +
  labs(
    color = "w parameters",
    fill = "w parameters",
    x = "weight"
  ) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos_w_parameters.png",
       width = 7, height = 5)
```

```{r}
weights_draws_df %>%
  filter(w_param_cond == "1,0,0,0,0") %>%
  ggplot() +
  geom_density(
    aes(
      x = weights, fill = as.character(c_parameter)
    ),
    alpha = .4
  ) +
  geom_vline(aes(xintercept = w_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ feature_number) +
  scale_fill_brewer(palette = "PuOr") +
  labs(
    color = "c parameters",
    fill = "c parameters"
  ) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos-w_1_by_c.png",
       width = 7, height = 5)
```

```{r}
weights_draws_df %>%
  filter(w_param_cond == "0.2,0.2,0.2,0.2,0.2") %>%
  ggplot() +
  geom_density(
    aes(
      x = weights, fill = as.character(c_parameter)
    ),
    alpha = .4
  ) +
  geom_vline(aes(xintercept = w_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ feature_number) +
  scale_fill_brewer(palette = "PuOr") +
  labs(
    color = "c parameters",
    fill = "c parameters"
  ) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos-w_2_by_c.png",
       width = 7, height = 5)
```

```{r}
weights_draws_df %>%
  filter(w_param_cond == "1,0,0,0,0") %>%
  ggplot() +
  geom_density(
    aes(
      x = weights, fill = as.character(nobservations)
    ),
    alpha = .4
  ) +
  geom_vline(aes(xintercept = w_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ feature_number) +
  scale_fill_brewer(palette = "Dark2") +
  labs(
    fill = "Number of observations"
  ) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos-w_1_by_nobs.png",
       width = 7, height = 5)
```

```{r}
weights_draws_df %>%
  filter(w_param_cond == "0.2,0.2,0.2,0.2,0.2") %>%
  ggplot() +
  geom_density(
    aes(
      x = weights, fill = as.character(nobservations)
    ),
    alpha = .4
  ) +
  geom_vline(aes(xintercept = w_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ feature_number) +
  scale_fill_brewer(palette = "Dark2") +
  labs(
    fill = "Number of observations"
  ) +
  theme(legend.position = "bottom")

ggsave("figs/gcm/parameter_recovery/pos-w_2_by_nobs.png",
       width = 7, height = 5)
```

## Reinforcement Learning
### load data
```{r}
nobservations <- c(104, 208, 312)

rm(recovery_df) # remove in case it is already defined
# read df
for (nobs in nobservations) {
  tmp <- read_csv(
    paste("data/recovery/parameter_recovery_rl_binary",
      nobs, "_1.csv",
      sep = ""
    )
  )

  if (exists("recovery_df")) {
    recovery_df <- rbind(recovery_df, tmp)
  } else {
    recovery_df <- tmp
  }
}

recovery_df <- recovery_df %>%
  mutate(
    true_alpha_pos_round = round(true_alpha_pos, 3),
    true_alpha_neg_round = round(true_alpha_neg, 3),
    true_temp_round = round(true_temp, 3)
  )
```

### inspection
```{r}
recovery_df %>%
  group_by(true_alpha_neg) %>%
  summarize(
    mean_alpha_neg = mean(alpha_neg),
    sd_alpha_neg = sd(alpha_neg),
    mean_alpha_neg_prior = mean(alpha_neg_prior),
    sd_alpha_neg_prior = sd(alpha_neg_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = true_alpha_neg), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_alpha_neg_round) +
  xlab(latex2exp::TeX("$\\alpha_-$"))

p + labs(
  title = "Prior Posterior update: Alpha_negative",
  caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl/parameter_recovery/pos-prior-update-alpha-neg.png", p,
  width = 7, height = 5
)
```

```{r}
recovery_df %>%
  group_by(true_alpha_pos) %>%
  summarize(
    mean_alpha_pos = mean(alpha_pos),
    sd_alpha_pos = sd(alpha_pos),
    mean_alpha_pos_prior = mean(alpha_pos_prior),
    sd_alpha_pos_prior = sd(alpha_pos_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = true_alpha_pos), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_alpha_pos_round) +
  xlab(latex2exp::TeX("$\\alpha_+$"))

p + labs(
  title = "Prior Posterior update: Alpha_positive",
  caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl/parameter_recovery/pos-prior-update-alpha-pos.png", p,
  width = 7, height = 5
)
```

```{r}
neg <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_alpha_neg_round), y = true_alpha_neg, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  xlab(latex2exp::TeX("True $\\alpha_-$")) +
  ylab(latex2exp::TeX("$\\alpha_-$"))

pos <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_alpha_pos_round), y = true_alpha_pos, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  xlab(latex2exp::TeX("True $\\alpha_+$")) +
  ylab(latex2exp::TeX("$\\alpha_+$"))

p <- neg + pos

p +
  plot_annotation(title = "Posterior Distributions of Alphas")
ggsave("figs/rl/parameter_recovery/pos-alphas.png", p,
  width = 7, height = 5
)
```

```{r}
neg <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_alpha_neg_round), y = true_alpha_neg, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  xlab("True Alpha") +
  ylab("Alpha Negative")

pos <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_alpha_pos_round), y = true_alpha_pos, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  xlab("True Alpha") +
  ylab("Alpha Postive")

p <- neg + pos

p +
  plot_annotation(title = "Posterior Distributions of Alphas by Temperature")
ggsave("figs/rl/parameter_recovery/pos-alphas_by_temp.png", p,
  width = 7, height = 5
)
```

```{r}
p1 <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = alpha_neg,
      fill = as.character(nobservations)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_alpha_neg), linetype = "dashed") +
  theme_bw() +
  labs(fill = "Number of observations") +
  facet_wrap(. ~ true_alpha_neg_round, scale = "free") +
  xlab(latex2exp::TeX("$\\alpha_-$")) +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Alpha_negative")
ggsave("figs/rl/parameter_recovery/pos-alpha-neg_by_nobs.png", p1,
  width = 7, height = 5
)
```

```{r}
p2 <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = alpha_pos,
      fill = as.character(nobservations)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_alpha_pos), linetype = "dashed") +
  theme_bw() +
  labs(fill = "Number of observations") +
  facet_wrap(. ~ true_alpha_pos_round) +
  xlab(latex2exp::TeX("$\\alpha_+$")) +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Alpha_positive")
ggsave("figs/rl/parameter_recovery/pos-alpha-pos_by_nobs.png", p2,
  width = 7, height = 5
)
```

```{r}
p1 / p2 +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```

```{r}
p1 <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = alpha_neg,
      fill = as.factor(true_temp_round)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_alpha_neg), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_alpha_neg_round, scale = "free") +
  labs(fill = latex2exp::TeX("$\\tau$")) +
  xlab(latex2exp::TeX("$\\alpha_-$")) +
  scale_fill_brewer(
    palette = "PuOr"
  ) +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Alpha_negative")
ggsave("figs/rl/parameter_recovery/pos-alpha-neg_by_temp.png", p1,
  width = 7, height = 5
)
```

```{r}
p2 <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = alpha_pos,
      fill = as.factor(true_temp_round)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_alpha_pos), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_alpha_pos_round) +
  labs(fill = latex2exp::TeX("$\\tau$")) +
  xlab(latex2exp::TeX("$\\alpha_+$")) +
  scale_fill_brewer(
    palette = "PuOr"
  ) +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Alpha_positive")
ggsave("figs/rl/parameter_recovery/pos-alpha-pos_by_temp.png", p2,
  width = 7, height = 5
)
```

```{r}
p1 / p2 +
  plot_layout(guides = "collect") &
  theme(legend.position = "bottom")
```

```{r}
recovery_df %>%
  group_by(true_temp) %>%
  summarize(
    mean_temp = mean(temp),
    sd_temp = sd(temp),
    mean_temp_prior = mean(temp_prior),
    sd_temp_prior = sd(temp_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = temp), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  xlab(latex2exp::TeX("$\\tau$"))

p + labs(
  title = "Prior Posterior update: Temperature",
  caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl/parameter_recovery/pos-prior-update-temp.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = temp,
      fill = as.character(nobservations)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  labs(fill = "Number of observations") +
  xlab(latex2exp::TeX("$\\tau$")) +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Temperature")
ggsave("figs/rl/parameter_recovery/pos-temp_by_nobs.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_temp_round), y = temp),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_temp_round), y = temp),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_temp_round), y = true_temp, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  xlab(latex2exp::TeX("True $\\tau$")) +
  ylab(latex2exp::TeX("$\\tau$"))

p + labs(title = "Posterior Distributions of Temperature")
ggsave("figs/rl/parameter_recovery/pos-temp.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = temp,
      fill = as.character(true_alpha_neg_round)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  labs(fill = latex2exp::TeX("$\\alpha_-$")) +
  xlab(latex2exp::TeX("$\\tau$")) +
  scale_fill_brewer(palette = "PuOr") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Temperature")
ggsave("figs/rl/parameter_recovery/pos-temp_by_alpha_neg.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = temp,
      fill = as.character(true_alpha_pos_round)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  labs(fill = latex2exp::TeX("$\\alpha_+$")) +
  xlab(latex2exp::TeX("$\\tau$")) +
  scale_fill_brewer(palette = "PuOr") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Temperature")
ggsave("figs/rl/parameter_recovery/pos-temp_by_alpha_pos.png", p,
  width = 7, height = 5
)
```

## Reinforcement Learning Simple
### load data
```{r}
nobservations <- c(104, 208, 312)

rm(recovery_df) # remove in case it is already defined
# read df
for (nobs in nobservations) {
  tmp <- read_csv(
    paste("data/recovery/parameter_recovery_rl_simple_binary",
      nobs, "_1.csv",
      sep = ""
    )
  )

  if (exists("recovery_df")) {
    recovery_df <- rbind(recovery_df, tmp)
  } else {
    recovery_df <- tmp
  }
}

recovery_df <- recovery_df %>%
  mutate(
    true_alpha_round = round(true_alpha, 3),
    true_temp_round = round(true_temp, 3)
  )
```

### inspection
```{r}
recovery_df %>%
  group_by(true_alpha) %>%
  summarize(
    mean_alpha = mean(alpha),
    sd_alpha = sd(alpha),
    mean_alpha_prior = mean(alpha_prior),
    sd_alpha_prior = sd(alpha_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(aes(x = alpha_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = alpha), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = true_alpha), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_alpha_round) +
  xlab(latex2exp::TeX("$\\alpha$"))

p + labs(
  title = "Prior Posterior update: Alpha",
  caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl_simple/parameter_recovery/pos-prior-update-alpha.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_alpha_round), y = alpha),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_alpha_round), y = alpha),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_alpha_round), y = true_alpha, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  xlab(latex2exp::TeX("True $\\alpha$")) +
  ylab(latex2exp::TeX("$\\alpha$"))

p + labs(title = "Posterior Distribution of Alpha")
ggsave("figs/rl_simple/parameter_recovery/pos-alpha.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = alpha,
      fill = as.character(nobservations)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_alpha), linetype = "dashed") +
  theme_bw() +
  labs(fill = "Number of observations") +
  facet_wrap(. ~ true_alpha_round) +
  xlab(latex2exp::TeX("$\\alpha$")) +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Alpha")
ggsave("figs/rl_simple/parameter_recovery/pos-alpha_by_nobs.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = alpha,
      fill = as.factor(true_temp_round)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_alpha), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_alpha_round) +
  labs(fill = latex2exp::TeX("$\\tau$")) +
  xlab(latex2exp::TeX("$\\alpha$")) +
  scale_fill_brewer(
    palette = "PuOr"
  ) +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Alpha")
ggsave("figs/rl_simple/parameter_recovery/pos-alpha_by_temp.png", p,
  width = 7, height = 5
)
```

```{r}
recovery_df %>%
  group_by(true_temp) %>%
  summarize(
    mean_temp = mean(temp),
    sd_temp = sd(temp),
    mean_temp_prior = mean(temp_prior),
    sd_temp_prior = sd(temp_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = temp), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  xlab(latex2exp::TeX("$\\tau$"))

p + labs(
  title = "Prior Posterior update: Temperature",
  caption = "Prior (blue) and posterior (red)"
)
ggsave("figs/rl_simple/parameter_recovery/pos-prior-update-temp.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = temp,
      fill = as.character(nobservations)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  labs(fill = "Number of observations") +
  xlab(latex2exp::TeX("$\\tau$")) +
  scale_fill_brewer(palette = "Dark2") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior update: Temperature")
ggsave("figs/rl_simple/parameter_recovery/pos-temp_by_nobs.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_violin(
    aes(x = as.factor(true_temp_round), y = temp),
    fill = "red", alpha = 0.3
  ) +
  geom_boxplot(
    aes(x = as.factor(true_temp_round), y = temp),
    width = 0.1
  ) +
  geom_line(
    aes(x = as.factor(true_temp_round), y = true_temp, group = 1),
    linetype = "dashed"
  ) +
  theme_bw() +
  xlab(latex2exp::TeX("True $\\tau$")) +
  ylab(latex2exp::TeX("$\\tau$"))

p + labs(title = "Posterior Distributions of Temperature")
ggsave("figs/rl_simple/parameter_recovery/pos-temp.png", p,
  width = 7, height = 5
)
```

```{r}
p <- ggplot(data = recovery_df) +
  geom_density(
    aes(
      x = temp,
      fill = as.factor(true_alpha_round)
    ),
    alpha = .5
  ) +
  geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ true_temp_round) +
  labs(fill = latex2exp::TeX("$\\alpha$")) +
  xlab(latex2exp::TeX("$\\tau$")) +
  scale_fill_brewer(palette = "PuOr") +
  theme(legend.position = "bottom")

p + labs(title = "Posterior Distributions of Temperature by Alpha")
ggsave("figs/rl_simple/parameter_recovery/pos-temp_by_alpha.png", p,
  width = 7, height = 5
)
```