# Visualizations for priors

```{r}
# libraries
library(pacman)
pacman::p_load(
    tidyverse,
    boot,
    RColorBrewer,
    latex2exp
)
```

## GCM

c parameter
```{r}
grid <- 100
ncs <- 11

distances <- seq(from = 0, to = 5, length.out = grid)
cs <- seq(from = 0, to = 2, length.out = ncs)

tibble(
    distance = rep(distances, each = ncs),
    c = rep(cs, grid)
) %>%
    mutate(
        similarity = exp(-c * distance)
    ) %>%
    ggplot() +
    geom_line(aes(x = distance, y = similarity, group = c, color = c)) +
    theme_classic() +
    scale_color_distiller(palette = "PuOr") +
    labs(
        color = "c"
    )

ggsave("figs/gcm/prior_c.png", width = 7, height = 7)
```

## Reinforcement learning

Temperature
```{r}
grid <- 100
ntemps <- 11

values <- seq(from = -1, to = 1, length.out = grid)
temperatures <- seq(from = 0, to = 5, length.out = ntemps)

tibble(
    value = rep(values, each = ntemps),
    temperature = rep(temperatures, grid)
) %>%
    mutate(
        probability = boot::inv.logit(temperature * value)
    ) %>%
    ggplot() +
    geom_line(aes(
        x = value, y = probability,
        group = temperature, color = temperature
    )) +
    theme_classic() +
    scale_color_distiller(palette = "PuOr") +
    labs(
        color = latex2exp::TeX("$\\tau$")
    )

ggsave("figs/rl/prior_temp.png", width = 7, height = 7)
```