# Model fit
```{r}
# libraries
library(pacman)
pacman::p_load(
    tidyverse,
    patchwork
)
```

## GCM

## Reinforcement Learning (assymetrical)
### load data
```{r}
aliendata <- read_csv("data/AlienData.csv") %>%
                filter(session == 1) %>%
                mutate(
                    subject = ifelse(condition == 2, subject + 100, subject)
                )

draws_df <- read_csv("data/rl_samples.csv")

# update colnames
new_colnames <- c()
for (colname in colnames(draws_df)) {
    if (grepl("values_prior", colname, fixed = TRUE)) { # specific case
        new_colname <- paste("values_prior_",
            str_extract_all(colname, "\\d+")[[1]][1], "_",
            str_extract_all(colname, "\\d+")[[1]][2],
            sep = ""
        )
        new_colnames <- c(new_colnames, new_colname)
    } else if (grepl(",", colname, fixed = TRUE)) { # matrix
        new_colname <- paste(str_extract(colname, "\\w+"), "_",
            str_extract_all(colname, "\\d+")[[1]][1], "_",
            str_extract_all(colname, "\\d+")[[1]][2],
            sep = ""
        )
        new_colnames <- c(new_colnames, new_colname)
    } else if (grepl("[", colname, fixed = TRUE)) { # array
        new_colname <- paste(str_extract(colname, "\\w+"), "_",
            str_extract(colname, "\\d+"),
            sep = ""
        )
        new_colnames <- c(new_colnames, new_colname)
    } else {
        new_colnames <- c(new_colnames, colname)
    }
}
colnames(draws_df) <- new_colnames
```

### inspection
Chains
```{r}
p1 <- ggplot(draws_df) +
    geom_line(aes(.iteration, temp, group = .chain, color = .chain)) +
    theme_bw() +
    labs(y = "Temperature")

p2 <- ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_neg, group = .chain, color = .chain)) +
    theme_bw() +
    labs(y = "Alpha Negative")

p3 <- ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_pos, group = .chain, color = .chain)) +
    theme_bw() +
    labs(y = "Alpha Positive")

p1 / p2 / p3 +
    plot_annotation(title = "Chain iterations")

ggsave("figs/rl/chain_iterations.png")
```

```{r}
ggplot(draws_df) +
    geom_line(aes(.iteration, temp, group = .chain, color = .chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(y = "Temperature")

ggsave("figs/rl/chain_iterations_temp.png")

ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_neg, group = .chain, color = .chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(y = "Alpha Negative")

ggsave("figs/rl/chain_iterations_alphaneg.png")

ggplot(draws_df) +
    geom_line(aes(.iteration, alpha_pos, group = .chain, color = .chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(y = "Alpha Positive")

ggsave("figs/rl/chain_iterations_alphapos.png")
```

```{r}
p1 <- ggplot(draws_df) +
    geom_point(
        aes(alpha_neg, alpha_pos, group = .chain, color = .chain),
        alpha = 0.1
    ) +
    theme_bw() +
    labs(x = "alpha negative", y = "alpha positive")

p2 <- ggplot(draws_df) +
    geom_point(
        aes(alpha_neg, temp, group = .chain, color = .chain),
        alpha = 0.1
    ) +
    theme_bw() +
    labs(x = "alpha negative", y = "temperature")

p3 <- ggplot(draws_df) +
    geom_point(
        aes(alpha_pos, temp, group = .chain, color = .chain),
        alpha = 0.1
    ) +
    theme_bw() +
    labs(x = "alpha positive", y = "temperature")

p1 / (p2 + p3)

ggsave("figs/rl/chains_correlation.png", width = 7)
```

Theta
```{r}
p1 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = theta_prior_2),
        fill = "purple", alpha = .5
    ) +
    geom_density(
        aes(x = theta_prior_52),
        fill = "yellow", alpha = .5
    ) +
    geom_density(
        aes(x = theta_prior_104),
        fill = "red", alpha = .5
    ) +
    facet_wrap(. ~ subject) +
    theme_bw() +
    ylim(0, 30)

p2 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = theta_2),
        fill = "purple", alpha = .5
    ) +
    geom_density(
        aes(x = theta_52),
        fill = "yellow", alpha = .5
    ) +
    geom_density(
        aes(x = theta_104),
        fill = "red", alpha = .5
    ) +
    facet_wrap(. ~ subject) +
    theme_bw() +
    ylim(0, 30)

p1 + p2
```

Alpha parameters
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_alpha_neg = mean(alpha_neg),
        sd_alpha_neg = sd(alpha_neg),
        mean_alpha_neg_prior = mean(alpha_neg_prior),
        sd_alpha_neg_prior = sd(alpha_neg_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(
        title = "Prior Posterior update: Alpha_negative",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Alpha_negative")

ggsave("figs/rl/prior-pos-update-alphaneg.png")
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    labs(
        title = "Prior Posterior update: Alpha_negative",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Alpha_negative")

ggsave("figs/rl/prior-pos-update-alphaneg-condtion.png")
```

```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_alpha_pos = mean(alpha_pos),
        sd_alpha_pos = sd(alpha_pos),
        mean_alpha_pos_prior = mean(alpha_pos_prior),
        sd_alpha_pos_prior = sd(alpha_pos_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(
        title = "Prior Posterior update: Alpha_positive",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Alpha_positive")

ggsave("figs/rl/prior-pos-update-alphapos.png")
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    labs(
        title = "Prior Posterior update: Alpha_positive",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Alpha_positive")

ggsave("figs/rl/prior-pos-update-alphapos-condition.png")
```

Temperature
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_temp = mean(temp),
        sd_temp = sd(temp),
        mean_temp_prior = mean(temp_prior),
        sd_temp_prior = sd(temp_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(
        title = "Prior Posterior update: Temperature",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Temperature")

ggsave("figs/rl/prior-pos-update-temp.png")
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    labs(
        title = "Prior Posterior update: Temperature",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Temperature")

ggsave("figs/rl/prior-pos-update-temp-condition.png")
```

Values
```{r}
draws_df %>%
    summarize(
        mean(values_1_1),
        # sd(values_1_1),
        mean(values_1_2),
        # sd(values_1_2),
        mean(values_1_3),
        # sd(values_1_3),
        mean(values_1_4),
        # sd(values_1_4),
        mean(values_1_5),
        # sd(values_1_5)
    )
```

```{r}
p1 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = values_prior_1_1),
        fill = "blue", alpha = .3
    ) +
    geom_density(
        aes(x = values_prior_1_2),
        fill = "purple", alpha = .3
    ) +
    geom_density(
        aes(x = values_prior_1_3),
        fill = "red", alpha = .3
    ) +
    geom_density(
        aes(x = values_prior_1_4),
        fill = "yellow", alpha = .3
    ) +
    geom_density(
        aes(x = values_prior_1_5),
        fill = "green", alpha = .3
    ) +
    theme_bw() +
    labs(x = "Value", title = "Prior Values")

p2 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = values_1_1),
        fill = "blue", alpha = .3
    ) +
    geom_density(
        aes(x = values_1_2),
        fill = "purple", alpha = .3
    ) +
    geom_density(
        aes(x = values_1_3),
        fill = "red", alpha = .3
    ) +
    geom_density(
        aes(x = values_1_4),
        fill = "yellow", alpha = .3
    ) +
    geom_density(
        aes(x = values_1_5),
        fill = "green", alpha = .3
    ) +
    theme_bw() +
    labs(x = "Value", title = "Posterior Values")

p1 + p2
```

```{r}
for (f in 1:5) {
    value_f_0 <- paste("values_1_", f, sep = "")
    value_f_1 <- paste("values_2_", f, sep = "")
    p <- ggplot(draws_df) +
        geom_density(
            aes_string(x = value_f_0),
            fill = "orange", alpha = .3
        ) +
        geom_density(
            aes_string(x = value_f_1),
            fill = "purple", alpha = .3
        ) +
        theme_bw() +
        labs(
            title = paste("Feature", f),
            x = "value"
        )

    assign(paste("p", f, sep = ""), p)
}

p1 + p2 + p3 + p4 + p5
```

```{r}
p1 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = values_2_1),
        fill = "blue", alpha = .1
    ) +
    geom_density(
        aes(x = values_2_2),
        fill = "purple", alpha = .1
    ) +
    geom_density(
        aes(x = values_2_3),
        fill = "red", alpha = .1
    ) +
    geom_density(
        aes(x = values_2_4),
        fill = "yellow", alpha = .1
    ) +
    geom_density(
        aes(x = values_2_5),
        fill = "green", alpha = .1
    ) +
    theme_bw() +
    labs(x = "Value", title = "Feature = 0")

p2 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = values_1_1),
        fill = "blue", alpha = .1
    ) +
    geom_density(
        aes(x = values_1_2),
        fill = "purple", alpha = .1
    ) +
    geom_density(
        aes(x = values_1_3),
        fill = "red", alpha = .1
    ) +
    geom_density(
        aes(x = values_1_4),
        fill = "yellow", alpha = .1
    ) +
    geom_density(
        aes(x = values_1_5),
        fill = "green", alpha = .1
    ) +
    theme_bw() +
    labs(x = "Value", title = "Feature = 1")

p1 + p2
```

Posterior prediction
```{r}
draws_df %>%
    group_by(condition, session) %>%
    summarize(
        correct_1 = mean(posteriorcorrect_1),
        correct_50 = mean(posteriorcorrect_50),
        correct_96 = mean(posteriorcorrect_96),
        correct_104 = mean(posteriorcorrect_104)
    )
```

```{r}
p1 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = priorcorrect_1),
        fill = "blue", alpha = .3
    ) +
    geom_density(
        aes(x = priorcorrect_50),
        fill = "purple", alpha = .3
    ) +
    geom_density(
        aes(x = priorcorrect_96),
        fill = "red", alpha = .3
    ) +
    geom_density(
        aes(x = priorcorrect_104),
        fill = "yellow", alpha = .3
    ) +
    theme_bw() +
    labs(x = "correct category")

p2 <- ggplot(data = draws_df) +
    geom_density(
        aes(x = posteriorcorrect_1),
        fill = "blue", alpha = .3
    ) +
    geom_density(
        aes(x = posteriorcorrect_50),
        fill = "purple", alpha = .3
    ) +
    geom_density(
        aes(x = posteriorcorrect_96),
        fill = "red", alpha = .3
    ) +
    geom_density(
        aes(x = posteriorcorrect_104),
        fill = "yellow", alpha = .1
    ) +
    theme_bw() +
    labs(x = "correct category")

p1 + p2
```

```{r}
rm(posteriorcorrect)

for (t in 1:104) {
    for (s in unique(draws_df$subject)) {
        tmp_draws <- draws_df %>%
            filter(subject == s)
        col <- paste("tmp_draws$posteriorcorrect_", t, sep = "")
        colvalues <- eval(parse(text = col))
        mean_correct <- mean(colvalues)
        sd_correct <- sd(colvalues)
        tmp <- tibble(
            correct = mean_correct,
            sd = sd_correct,
            trial = t,
            condition = unique(tmp_draws$condition),
            subject = s
        )

        if (exists("posteriorcorrect")) {
            posteriorcorrect <- rbind(
                posteriorcorrect, tmp
            )
        } else {
            posteriorcorrect <- tmp
        }
    }
}
```

```{r}
posteriorcorrect <- posteriorcorrect %>%
                    mutate(
                        condition = as.factor(condition),
                        subject = as.factor(subject),
                        type = "simulated"
                    ) %>%
                    group_by(subject) %>%
                    mutate(
                        cumulative = cumsum(correct) / trial
                    )

real_correct <- aliendata %>%
                select(c(condition, subject, correct, trial)) %>%
                mutate(
                    condition = as.factor(condition),
                    subject = as.factor(subject),
                    sd = 0,
                    type = "real",
                    cumulative = cumsum(correct) / trial
                ) %>% 
                group_by(subject) %>%
                mutate(
                    cumulative = cumsum(correct) / trial
                )

posteriorcorrect <- rbind(posteriorcorrect, real_correct)

ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = correct, color = type)) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    theme_bw() + facet_wrap(. ~ subject) +
    scale_color_manual(values = c("orange", "purple"))

ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = correct, color = type)) +
    geom_smooth(aes(x = trial, y = correct, color = type)) +
    geom_vline(aes(xintercept = 96), linetype = "dashed") +
    theme_bw() + facet_wrap(. ~ condition) +
    scale_color_manual(values = c("orange", "purple"))
```

```{r}
ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = cumulative, color = type)) +
    geom_line(aes(x = trial, y = cumulative, color = type)) +
    theme_bw() + facet_wrap(. ~ subject) +
    scale_color_manual(values = c("orange", "purple"))

ggplot(data = posteriorcorrect) +
    geom_point(aes(x = trial, y = cumulative, color = type)) +
    geom_smooth(aes(x = trial, y = cumulative, color = type)) +
    geom_vline(aes(xintercept = 96), linetype = "dashed") +
    theme_bw() + facet_wrap(. ~ condition) +
    scale_color_manual(values = c("orange", "purple"))
```

## Reinforcement Learning (simple)
### load data
```{r}
draws_df <- read_csv("data/rl_simple_samples.csv")

# update colnames
new_colnames <- c()
for (colname in colnames(draws_df)) {
    if (grepl("values_prior", colname, fixed = TRUE)) { # specific case
        new_colname <- paste("values_prior_",
            str_extract_all(colname, "\\d+")[[1]][1], "_",
            str_extract_all(colname, "\\d+")[[1]][2],
            sep = ""
        )
        new_colnames <- c(new_colnames, new_colname)
    } else if (grepl(",", colname, fixed = TRUE)) { # matrix
        new_colname <- paste(str_extract(colname, "\\w+"), "_",
            str_extract_all(colname, "\\d+")[[1]][1], "_",
            str_extract_all(colname, "\\d+")[[1]][2],
            sep = ""
        )
        new_colnames <- c(new_colnames, new_colname)
    } else if (grepl("[", colname, fixed = TRUE)) { # array
        new_colname <- paste(str_extract(colname, "\\w+"), "_",
            str_extract(colname, "\\d+"),
            sep = ""
        )
        new_colnames <- c(new_colnames, new_colname)
    } else {
        new_colnames <- c(new_colnames, colname)
    }
}
colnames(draws_df) <- new_colnames
```

### inspection
Chains
```{r}
p1 <- ggplot(draws_df) +
    geom_line(aes(.iteration, temp, group = .chain, color = .chain)) +
    theme_bw() +
    labs(y = "Temperature")

p2 <- ggplot(draws_df) +
    geom_line(aes(.iteration, alpha, group = .chain, color = .chain)) +
    theme_bw() +
    labs(y = "Alpha")

p1 / p2 +
    plot_annotation(title = "Chain iterations")

ggsave("figs/rl_simple/chain_iterations.png")
```

```{r}
ggplot(draws_df) +
    geom_line(aes(.iteration, temp, group = .chain, color = .chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(y = "Temperature")

ggsave("figs/rl_simple/chain_iterations_temp.png")

ggplot(draws_df) +
    geom_line(aes(.iteration, alpha, group = .chain, color = .chain)) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(y = "Alpha")

ggsave("figs/rl_simple/chain_iterations_alpha.png")
```

```{r}
ggplot(draws_df) +
    geom_point(
        aes(alpha, temp, group = .chain, color = .chain),
        alpha = 0.1
    ) +
    theme_bw() +
    labs(x = "alpha", y = "temperature")

ggsave("figs/rl_simple/chains_correlation.png", width = 7)
```

Alpha parameter
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_alpha = mean(alpha),
        sd_alpha = sd(alpha),
        mean_alpha_prior = mean(alpha_prior),
        sd_alpha_prior = sd(alpha_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(
        title = "Prior Posterior update: Alpha",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Alpha")

ggsave("figs/rl_simple/prior-pos-update-alpha.png")
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = alpha_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    labs(
        title = "Prior Posterior update: Alpha",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Alpha")

ggsave("figs/rl_simple/prior-pos-update-alpha-condtion.png")
```

Temperature
```{r}
draws_df %>%
    group_by(condition) %>%
    summarize(
        mean_temp = mean(temp),
        sd_temp = sd(temp),
        mean_temp_prior = mean(temp_prior),
        sd_temp_prior = sd(temp_prior)
    )
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ subject) +
    labs(
        title = "Prior Posterior update: Temperature",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Temperature")

ggsave("figs/rl_simple/prior-pos-update-temp.png")
```

```{r}
ggplot(data = draws_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    theme_bw() +
    facet_wrap(. ~ condition) +
    labs(
        title = "Prior Posterior update: Temperature",
        caption = "Prior (blue) and posterior (red)"
    ) +
    xlab("Temperature")

ggsave("figs/rl_simple/prior-pos-update-temp-condition.png")
```
