# Parameter recovery 

```{r}
# libraries
library(pacman)
pacman::p_load(
  tidyverse,
  cmdstanr,
  posterior,
  patchwork,
  future,
  purrr,
  furrr
)

source("../src/fit_param_recov.r")
source("../src/generative_models.r")
source("../src/util.r")
```

## GCM
```{r}
# load model
# set_cmdstan_path('/work/MA_thesis/cmdstan-2.31.0')
file <- file.path("../stan/gcm.stan")

mod <- cmdstan_model(
  file,
  cpp_options = list(stan_threads = TRUE),
  # stanc_options = list("O1")
)
print("Done compiling!")
```

### Simulate and run model
```{r}
# multi cores
plan(multisession, workers = 4)

# parameters for observations
n_obs <- 208
n_features <- 5
type <- "continuous"

# model parameters
c_parameters <- seq(from = 0, to = 2, length.out = 6)
w_parameters <- c("1,0,0,0,0", "0.2,0.2,0.2,0.2,0.2")

# run model
parameters <- tibble(expand_grid(n_obs = n_obs,
                                 n_features = n_features,
                                 type = type,
                                 c = c_parameters,
                                 w = w_parameters)
               ) 

recovery_df <- future_pmap_dfr(parameters, 
                               param_recov_gcm, 
                               .options = furrr_options(seed = TRUE)
                               )
```

```{r}
# save df
# write.csv(recovery_df, paste("../data/recovery/parameter_recovery_gcm_", type, n_obs, ".csv", sep = ""))
```

```{r}
types <- c("binary")
nobservations <- c(104)

rm(recovery_df) # remove in case it is already defined
# read df
for (nobs in nobservations) {
  for (type in types) {
    tmp <- read_csv(
      paste("data/recovery/parameter_recovery_gcm_",
            type, nobs, "_1.csv", sep="")
    )

    if (exists("recovery_df")) {
        recovery_df <- rbind(recovery_df, tmp)
    } else {
        recovery_df <- tmp
    }
  }
}
```

### inspection
```{r}
ggplot(data = recovery_df) +
  geom_density(aes(x = c_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = c), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = c_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ c_parameter) + 
  labs(title = "Prior Posterior update: C parameter",
       caption = "Prior (blue) and posterior (red)") + 
  xlab("C")
```

```{r}
w_parameters <- unique(recovery_df$w_parameter)
filter_w_param <- w_parameters[1]

recovery_df %>% filter(w_parameter == filter_w_param) %>% ggplot() +
  geom_density(aes(x = c_prior), fill = "blue", alpha = .5) +
  geom_density(aes(x = c), fill = "red", alpha = .5) +
  geom_vline(aes(xintercept = c_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ c_parameter) + 
  labs(title = "Prior Posterior update: C parameter",
       subtitle = paste("filtered by w-parameter:", filter_w_param),
       caption = "Prior (blue) and posterior (red)") + 
  xlab("C")
```

```{r}
recovery_df %>%
  group_by(c_parameter) %>%
  summarize(
    mean_c = mean(c),
    sd_c = sd(c),
    mean_c_prior = mean(c_prior),
    sd_c_prior = sd(c_prior),
  )
```

```{r}
rm(weights_draws_df)

c_parameters <- unique(recovery_df$c_parameter)

for (c_param in c_parameters) {
  for (w_params in w_parameters){
    tmp <- recovery_df %>%
      filter(c_parameter == c_param & w_parameter == w_params) %>%
      pivot_longer(
        c("w[1]", "w[2]", "w[3]", "w[4]", "w[5]"),
        names_to = "features", values_to = "weights"
      ) %>%
      mutate(feature_number = str_extract(features, "\\d+")) %>%
      select(c(feature_number, weights)) %>%
      mutate(
        w_parameter = as.numeric(str_split(w_params, ",")[[1]])[as.integer(feature_number)],
        w_param_cond = w_params,
        c_parameter = c_param
      )
  
    if (exists("weights_draws_df")) {
      weights_draws_df <- rbind(weights_draws_df, tmp)
    } else {
      weights_draws_df <- tmp
    }
  }
}
```

```{r}
weights_draws_df %>%
  group_by(w_param_cond, feature_number) %>%
  summarize(
    w_mean = mean(weights),
    sd_w = sd(weights),
    true_w = unique(w_parameter)
  )
```


```{r}
ggplot(data = weights_draws_df) +
  geom_density(
    aes(
      x = weights, fill = w_param_cond,
      color = w_param_cond
    ),
    alpha = .2
  ) +
  geom_vline(aes(xintercept = w_parameter, color = w_param_cond), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ feature_number) + 
  labs(title = "Posterior for W parameter",
       color = "W parameters",
       fill = "W parameters")
```

```{r}
filter_w_param <- w_parameters[1]

weights_draws_df %>% filter(w_param_cond == filter_w_param) %>% 
  ggplot() +
  geom_density(
    aes(
      x = weights, fill = as.character(c_parameter),
      color = as.character(c_parameter)
    ),
    alpha = .2
  ) +
  geom_vline(aes(xintercept = w_parameter), linetype = "dashed") +
  theme_bw() +
  facet_wrap(. ~ feature_number) + 
  labs(title = "Posterior for W parameter",
       subtitle = paste("filtered by w-parameter:", filter_w_param),
       color = "C parameters",
       fill = "C parameters")
```

## Reinforcement Learning
```{r}
# load model
# set_cmdstan_path('/work/MA_thesis/cmdstan-2.31.0')
file <- file.path("../stan/reinforcement_learning.stan")

mod <- cmdstan_model(
  file,
  cpp_options = list(stan_threads = TRUE),
  # stanc_options = list("O1")
)
print("Done compiling!")
```

### Simulate and run model
```{r}
# multi cores
plan(multisession, workers = 4)

# parameters for observations
n_obs <- seq(from = 104, to = 104 * 3, length.out = 3)
n_features <- 5

# model parameters
alpha_parameters <- seq(from = 0, to = 1, length.out = 4)
temp_parameters <- seq(from = 0, to = 10, length.out = 4)

# run model
parameters <- tibble(expand_grid(n_obs = n_obs,
                                 n_features = n_features,
                                 type = "binary",  # only works with binary features
                                 alpha_pos = alpha_parameters,
                                 alpha_neg = alpha_parameters,
                                 temp = temp_parameters)
               ) 

recovery_df <- future_pmap_dfr(parameters, 
                               param_recov_rl, 
                               .options = furrr_options(seed = TRUE)
                               )
```

```{r}
# save df
# write.csv(recovery_df, paste("../data/recovery/parameter_recovery_rl.csv", sep = ""))
```

```{r}
nobservations <- c(104, 208, 312)

rm(recovery_df) # remove in case it is already defined
# read df
for (nobs in nobservations) {
  tmp <- read_csv(
    paste("data/recovery/parameter_recovery_rl_binary",
          nobs, "_2.csv", sep="")
  )

  if (exists("recovery_df")) {
    recovery_df <- rbind(recovery_df, tmp)
} else {
    recovery_df <- tmp
}
}

recovery_df <- recovery_df %>%
    mutate(
      true_alpha_pos_round = round(true_alpha_pos, 3),
      true_alpha_neg_round = round(true_alpha_neg, 3),
      true_temp_round = round(true_temp, 3)
    )
```

### inspection
```{r}
recovery_df %>% group_by(true_alpha_neg) %>%
  summarize(
   mean_alpha_neg = mean(alpha_neg),
   sd_alpha_neg = sd(alpha_neg),
   mean_alpha_neg_prior = mean(alpha_neg_prior),
   sd_alpha_neg_prior = sd(alpha_neg_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(aes(x = alpha_neg_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_neg), fill = "red", alpha = .5) +
    geom_vline(aes(xintercept = true_alpha_neg), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_alpha_neg_round) +
    labs(title = "Prior Posterior update: Alpha_negative",
         caption = "Prior (blue) and posterior (red)") +
    xlab("Alpha_negative")

p
ggsave("figs/parameter_recovery/pos-prior-update-alpha-neg.png", p)
```

```{r}
recovery_df %>% group_by(true_alpha_pos) %>%
  summarize(
   mean_alpha_pos = mean(alpha_pos),
   sd_alpha_pos = sd(alpha_pos),
   mean_alpha_pos_prior = mean(alpha_pos_prior),
   sd_alpha_pos_prior = sd(alpha_pos_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(aes(x = alpha_pos_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = alpha_pos), fill = "red", alpha = .5) +
    geom_vline(aes(xintercept = true_alpha_pos), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_alpha_pos_round) + 
    labs(title = "Prior Posterior update: Alpha_positive",
         caption = "Prior (blue) and posterior (red)") + 
    xlab("Alpha_positive")

p
ggsave("figs/parameter_recovery/pos-prior-update-alpha-pos.png", p)
```

```{r}
neg <- ggplot(data = recovery_df) +
    geom_violin(
      aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
      fill = "red", alpha = 0.3
      ) +
    geom_boxplot(
      aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
      width = 0.1
      ) +
    geom_line(
      aes(x = as.factor(true_alpha_neg_round), y = true_alpha_neg, group = 1),
      linetype = "dashed"
      ) +
    theme_bw() +
    xlab("True Alpha") + ylab("Alpha Negative")

pos <- ggplot(data = recovery_df) +
    geom_violin(
      aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
      fill = "red", alpha = 0.3
      ) +
    geom_boxplot(
      aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
      width = 0.1
      ) +
    geom_line(
      aes(x = as.factor(true_alpha_pos_round), y = true_alpha_pos, group = 1),
      linetype = "dashed"
      ) +
    theme_bw() +
    xlab("True Alpha") + ylab("Alpha Postive")

p <- neg + pos +
      plot_annotation(title = "Posterior Distributions of Alphas")

p
ggsave("figs/parameter_recovery/pos-alphas.png", p,
       width = 15, height = 10)
```

```{r}
neg <- ggplot(data = recovery_df) +
    geom_violin(
      aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
      fill = "red", alpha = 0.3
      ) +
    geom_boxplot(
      aes(x = as.factor(true_alpha_neg_round), y = alpha_neg),
      width = 0.1
      ) +
    geom_line(
      aes(x = as.factor(true_alpha_neg_round), y = true_alpha_neg, group = 1),
      linetype = "dashed"
      ) +
    theme_bw() + facet_wrap(. ~ true_temp_round) +
    xlab("True Alpha") + ylab("Alpha Negative")

pos <- ggplot(data = recovery_df) +
    geom_violin(
      aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
      fill = "red", alpha = 0.3
      ) +
    geom_boxplot(
      aes(x = as.factor(true_alpha_pos_round), y = alpha_pos),
      width = 0.1
      ) +
    geom_line(
      aes(x = as.factor(true_alpha_pos_round), y = true_alpha_pos, group = 1),
      linetype = "dashed"
      ) +
    theme_bw() + facet_wrap(. ~ true_temp_round) +
    xlab("True Alpha") + ylab("Alpha Postive")

p <- neg + pos +
    plot_annotation(title = "Posterior Distributions of Alphas by Temperature")

p
ggsave("figs/parameter_recovery/pos-alphas_by_temp.png", p,
       width = 15, height = 10)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(
        aes(
            x = alpha_neg,
            fill = as.character(nobservations)
        ),
        alpha = .5
    ) +
    geom_vline(aes(xintercept = true_alpha_neg), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_alpha_neg_round) +
    labs(title = "Posterior update: Alpha_negative",
         fill = "Number of observations") +
    xlab("Alpha_negative")

p
ggsave("figs/parameter_recovery/pos-alpha-neg_by_nobs.png", p)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(
        aes(
            x = alpha_pos,
            fill = as.character(nobservations)
        ),
        alpha = .5
    ) +
    geom_vline(aes(xintercept = true_alpha_pos), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_alpha_pos_round) +
    labs(title = "Posterior update: Alpha_positive",
         fill = "Number of observations") +
    xlab("Alpha_positive")

p
ggsave("figs/parameter_recovery/pos-alpha-pos_by_nobs.png", p)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(
        aes(
            x = alpha_neg,
            fill = as.factor(true_temp_round)
        ),
        alpha = .5
    ) +
    geom_vline(aes(xintercept = true_alpha_neg), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_alpha_neg_round) +
    labs(title = "Posterior update: Alpha_negative",
         fill = "Temperature") +
    xlab("Alpha_negative")

p
ggsave("figs/parameter_recovery/pos-alpha-neg_by_temp.png", p)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(
        aes(
            x = alpha_pos,
            fill = as.factor(true_temp_round)
        ),
        alpha = .5
    ) +
    geom_vline(aes(xintercept = true_alpha_pos), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_alpha_pos_round) +
    labs(title = "Posterior update: Alpha_positive",
         fill = "Temperature") +
    xlab("Alpha_positive")

p
ggsave("figs/parameter_recovery/pos-alpha-pos_by_temp.png", p)
```

```{r}
recovery_df %>% group_by(true_temp) %>% 
  summarize(
   mean_temp = mean(temp),
   sd_temp = sd(temp),
   mean_temp_prior = mean(temp_prior),
   sd_temp_prior = sd(temp_prior)
  )
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(aes(x = temp_prior), fill = "blue", alpha = .5) +
    geom_density(aes(x = temp), fill = "red", alpha = .5) +
    geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_temp_round) +
    labs(title = "Prior Posterior update: Temperature",
         caption = "Prior (blue) and posterior (red)") +
    xlab("Temperature")

p
ggsave("figs/parameter_recovery/pos-prior-update-temp.png", p)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_density(
        aes(
            x = temp,
            fill = as.character(nobservations)
        ),
        alpha = .5
    ) +
    geom_vline(aes(xintercept = true_temp), linetype = "dashed") +
    theme_bw() +
    facet_wrap(. ~ true_temp_round) +
    labs(title = "Posterior update: Temperature",
         fill = "Number of observations") +
    xlab("Temperature")

p
ggsave("figs/parameter_recovery/pos-temp_by_nobs.png", p)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_violin(
      aes(x = as.factor(true_temp_round), y = temp),
      fill = "red", alpha = 0.3
      ) +
    geom_boxplot(
      aes(x = as.factor(true_temp_round), y = temp),
      width = 0.1
      ) +
    geom_line(
      aes(x = as.factor(true_temp_round), y = true_temp, group = 1),
      linetype = "dashed"
      ) +
    theme_bw() +
    xlab("True Temperature") + ylab("Temperature") +
    labs(title = "Posterior Distributions of Temperature")

p
ggsave("figs/parameter_recovery/pos-temp.png", p)
```

```{r}
p <- ggplot(data = recovery_df) +
    geom_violin(
      aes(x = as.factor(true_temp_round), y = temp),
      fill = "red", alpha = 0.3
      ) +
    geom_boxplot(
      aes(x = as.factor(true_temp_round), y = temp),
      width = 0.1
      ) +
    geom_line(
      aes(x = as.factor(true_temp_round), y = true_temp, group = 1),
      linetype = "dashed"
      ) +
    theme_bw() + facet_wrap(. ~ true_alpha_neg_round) +
    xlab("True Temperature") + ylab("Temperature") +
    labs(title = "Posterior Distributions of Temperature by Alpha negative")

p
ggsave("figs/parameter_recovery/pos-temp_by_alpha_neg.png", p,
       width = 10, height = 10)
```